
<div id="center_country" class="center_country">
    <label for="center_country">البلد:</label>
    <select id="center_country" name="center_country" required>
        <option value="">اختر البلد</option>
        <option value="Afghanistan">Afghanistan - أفغانستان</option>
        <option value="Albania">Albania - ألبانيا</option>
        <option value="Algeria">Algeria - الجزائر</option>
        <option value="Andorra">Andorra - أندورا</option>
        <option value="Angola">Angola - أنغولا</option>
        <option value="Argentina">Argentina - الأرجنتين</option>
        <option value="Armenia">Armenia - أرمينيا</option>
        <option value="Australia">Australia - أستراليا</option>
        <option value="Austria">Austria - النمسا</option>
        <option value="Azerbaijan">Azerbaijan - أذربيجان</option>
        <option value="Bahamas">Bahamas - جزر البهاما</option>
        <option value="Bahrain">Bahrain - البحرين</option>
        <option value="Bangladesh">Bangladesh - بنغلاديش</option>
        <option value="Barbados">Barbados - باربادوس</option>
        <option value="Belarus">Belarus - بيلاروسيا</option>
        <option value="Belgium">Belgium - بلجيكا</option>
        <option value="Belize">Belize - بليز</option>
        <option value="Benin">Benin - بنين</option>
        <option value="Bhutan">Bhutan - بوتان</option>
        <option value="Bolivia">Bolivia - بوليفيا</option>
        <option value="Bosnia and Herzegovina">Bosnia and Herzegovina - البوسنة والهرسك</option>
        <option value="Botswana">Botswana - بوتسوانا</option>
        <option value="Brazil">Brazil - البرازيل</option>
        <option value="Brunei">Brunei - بروناي</option>
        <option value="Bulgaria">Bulgaria - بلغاريا</option>
        <option value="Burkina Faso">Burkina Faso - بوركينا فاسو</option>
        <option value="Burundi">Burundi - بوروندي</option>
        <option value="Cabo Verde">Cabo Verde - الرأس الأخضر</option>
        <option value="Cambodia">Cambodia - كمبوديا</option>
        <option value="Cameroon">Cameroon - الكاميرون</option>
        <option value="Canada">Canada - كندا</option>
        <option value="Central African Republic">Central African Republic - جمهورية أفريقيا الوسطى</option>
        <option value="Chad">Chad - تشاد</option>
        <option value="Chile">Chile - تشيلي</option>
        <option value="China">China - الصين</option>
        <option value="Colombia">Colombia - كولومبيا</option>
        <option value="Comoros">Comoros - جزر القمر</option>
        <option value="Congo, Democratic Republic of the">Congo, Democratic Republic of the - جمهورية الكونغو الديمقراطية</option>
        <option value="Congo, Republic of the">Congo, Republic of the - جمهورية الكونغو</option>
        <option value="Costa Rica">Costa Rica - كوستاريكا</option>
        <option value="Croatia">Croatia - كرواتيا</option>
        <option value="Cuba">Cuba - كوبا</option>
        <option value="Cyprus">Cyprus - قبرص</option>
        <option value="Czech Republic">Czech Republic - جمهورية التشيك</option>
        <option value="Denmark">Denmark - الدنمارك</option>
        <option value="Djibouti">Djibouti - جيبوتي</option>
        <option value="Dominica">Dominica - دومينيكا</option>
        <option value="Dominican Republic">Dominican Republic - جمهورية الدومينيكان</option>
        <option value="Ecuador">Ecuador - الإكوادور</option>
        <option value="Egypt">Egypt - مصر</option>
        <option value="El Salvador">El Salvador - السلفادور</option>
        <option value="Equatorial Guinea">Equatorial Guinea - غينيا الاستوائية</option>
        <option value="Eritrea">Eritrea - إريتريا</option>
        <option value="Estonia">Estonia - إستونيا</option>
        <option value="Eswatini">Eswatini - إسواتيني</option>
        <option value="Ethiopia">Ethiopia - إثيوبيا</option>
        <option value="Fiji">Fiji - فيجي</option>
        <option value="Finland">Finland - فنلندا</option>
        <option value="France">France - فرنسا</option>
        <option value="Gabon">Gabon - الغابون</option>
        <option value="Gambia">Gambia - غامبيا</option>
        <option value="Georgia">Georgia - جورجيا</option>
        <option value="Germany">Germany - ألمانيا</option>
        <option value="Ghana">Ghana - غانا</option>
        <option value="Greece">Greece - اليونان</option>
        <option value="Grenada">Grenada - غرينادا</option>
        <option value="Guatemala">Guatemala - غواتيمالا</option>
        <option value="Guinea">Guinea - غينيا</option>
        <option value="Guinea-Bissau">Guinea-Bissau - غينيا بيساو</option>
        <option value="Guyana">Guyana - غيانا</option>
        <option value="Haiti">Haiti - هايتي</option>
        <option value="Honduras">Honduras - هندوراس</option>
        <option value="Hungary">Hungary - المجر</option>
        <option value="Iceland">Iceland - آيسلندا</option>
        <option value="India">India - الهند</option>
        <option value="Indonesia">Indonesia - إندونيسيا</option>
        <option value="Iran">Iran - إيران</option>
        <option value="Iraq">Iraq - العراق</option>
        <option value="Ireland">Ireland - أيرلندا</option>
        <option value="Israel">Israel - إسرائيل</option>
        <option value="Italy">Italy - إيطاليا</option>
        <option value="Jamaica">Jamaica - جامايكا</option>
        <option value="Japan">Japan - اليابان</option>
        <option value="Jordan">Jordan - الأردن</option>
        <option value="Kazakhstan">Kazakhstan - كازاخستان</option>
        <option value="Kenya">Kenya - كينيا</option>
        <option value="Kiribati">Kiribati - كيريباتي</option>
        <option value="Kuwait">Kuwait - الكويت</option>
        <option value="Kyrgyzstan">Kyrgyzstan - قيرغيزستان</option>
        <option value="Laos">Laos - لاوس</option>
        <option value="Latvia">Latvia - لاتفيا</option>
        <option value="Lebanon">Lebanon - لبنان</option>
        <option value="Lesotho">Lesotho - ليسوتو</option>
        <option value="Liberia">Liberia - ليبيريا</option>
        <option value="Libya">Libya - ليبيا</option>
        <option value="Liechtenstein">Liechtenstein - ليختنشتاين</option>
        <option value="Lithuania">Lithuania - ليتوانيا</option>
        <option value="Luxembourg">Luxembourg - لوكسمبورغ</option>
        <option value="Madagascar">Madagascar - مدغشقر</option>
        <option value="Malawi">Malawi - مالاوي</option>
        <option value="Malaysia">Malaysia - ماليزيا</option>
        <option value="Maldives">Maldives - المالديف</option>
        <option value="Mali">Mali - مالي</option>
        <option value="Malta">Malta - مالطا</option>
        <option value="Marshall Islands">Marshall Islands - جزر مارشال</option>
        <option value="Micronesia">Micronesia - ميكرونيزيا</option>
        <option value="Moldova">Moldova - مولدوفا</option>
        <option value="Monaco">Monaco - موناكو</option>
        <option value="Mongolia">Mongolia - منغوليا</option>
        <option value="Montenegro">Montenegro - الجبل الأسود</option>
        <option value="Morocco">Morocco - المغرب</option>
        <option value="Mozambique">Mozambique - موزمبيق</option>
        <option value="Myanmar">Myanmar (بورما سابقاً)</option>
    </select>
</div>